# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'CompleteAutoLayout' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CompleteAutoLayout
  pod 'SnapKit'

end
